spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: cfnhfg
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
common:
  description: "Общие настройки для всех сервисов"
