server:
  port: 8082

eureka:
  instance:
    hostname: company-service # <--- Здесь должно быть имя сервиса Docker
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mickroservices_db
    username: postgres
    password: cfnhfg
    schema: company_schema
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: company_schema
    baseline-on-migrate: true
    create-schemas: true

service:
  description: "Сервис для управления компаниями"
