server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mickroservices_db
    username: postgres
    password: cfnhfg
    schema: company_schema

service:
  description: "Сервис для управления компаниями"
