server:
  port: 8082

spring:  
  # Настройки базы данных (оставил без изменений)
  datasource:
    url: jdbc:postgresql://postgres:5432/mickroservices_db
    username: postgres
    password: cfnhfg
    schema: company_schema
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: company_schema
    baseline-on-migrate: true
    create-schemas: true

  # --- НОВЫЕ НАСТРОЙКИ KAFKA ---
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: company-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

service:
  description: "Сервис для управления компаниями"
