server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mickroservices_db
    username: postgres
    password: cfnhfg
    schema: user_schema
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: user_schema
    baseline-on-migrate: true
    create-schemas: true

service:
  description: "Сервис для управления пользователями"
